version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: escolaVirtual-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a14s2e82
      MYSQL_DATABASE: escolavirtualDB
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
